name = "cloudflare-queues-scheduler"
main = "src/index.ts"
compatibility_date = "2024-01-01"
usage_model = 'bundled'


[vars]
ENVIRONMENT = 'production'

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "scheduler-db"
database_id = "aa0a2253-b40c-49c5-88a8-6d67671f8012"
migrations_table = "d1_migrations"
migrations_dir = "d1_migrations"
